baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: Conversion-assesment
primary: true
siteGroup: 4ce0c4e7-0ade-4470-9284-adfde6460ad0 # Conversion-assesment
sortOrder: 1
