dateModified: 1660437436
email:
  fromEmail: jvargas@conversionia.com
  fromName: Conversion-assesment
  replyToEmail: null
  template: ''
  transportSettings:
    apiKey: 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
    categories: ''
  transportType: putyourlightson\sendgrid\mail\SendgridAdapter
meta:
  __names__:
    1efe2a80-8045-41dd-ae04-8e64b18f4f03: Slides # Slides
    4ce0c4e7-0ade-4470-9284-adfde6460ad0: Conversion-assesment # Conversion-assesment
    15fcc23c-612d-4709-bd3c-6736f6d76d1e: Homepage # Homepage
    274b5f37-481f-47df-8ece-a277e6d6a399: Local # Local
    710c1936-f63d-4a3e-8ddd-1956d785b7ff: Text # Text
    dcaed4cd-b19b-4346-ae5d-ba0b781d29aa: Conversion-assesment # Conversion-assesment
    e10d1e8b-f7b3-427c-9be7-0f5c2fa8daae: Homepage # Homepage
    f57762b0-c0de-40bb-8373-43c2da606997: Common # Common
plugins:
  freeform:
    edition: pro
    enabled: true
    licenseKey: OKR72XNQPV90FAC6AQA3UBL0
    schemaVersion: 3.6.4
    settings:
      ajaxByDefault: true
      alertNotificationRecipients: null
      autoScroll: true
      autoScrollToErrors: true
      badgeType: all
      blockedEmails: null
      blockedEmailsError: 'Invalid Email Address'
      blockedIpAddresses: null
      blockedKeywords: null
      blockedKeywordsError: 'Invalid Entry Data'
      bypassSpamCheckOnLoggedInUsers: false
      clientDigestFrequency: 1
      clientDigestRecipients: null
      customErrorMessage: null
      customHoneypotName: null
      defaultTemplates: true
      defaultView: dashboard
      digestFrequency: 1
      digestOnlyOnProduction: false
      digestRecipients: null
      displayFeed: true
      emailTemplateDirectory: null
      emailTemplateStorage: db
      exportHandlesAsNames: false
      exportLabels: false
      fieldDisplayOrder: name
      fillWithGet: false
      footerScripts: false
      formFieldShowOnlyAllowedForms: false
      formSubmitDisable: true
      formSubmitExpiration: null
      formTemplateDirectory: null
      formattingTemplate: flexbox.html
      freeformHoneypot: true
      freeformHoneypotEnhancement: false
      hideBannerDemo: false
      hideBannerOldFreeform: false
      minimumSubmitTime: null
      pluginName: null
      purgableSpamAgeInDays: null
      purgableSubmissionAgeInDays: null
      purgableUnfinalizedAssetAgeInMinutes: 180
      recaptchaBehaviour: display_error
      recaptchaEnabled: false
      recaptchaErrorMessage: 'Please verify that you are not a robot.'
      recaptchaKey: null
      recaptchaLazyLoad: false
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      recaptchaSize: normal
      recaptchaTheme: light
      recaptchaType: v2_checkbox
      rememberPageSubmitOrder: true
      removeNewlines: false
      renderFormHtmlInCpViews: true
      salesforce_client_id: null
      salesforce_client_secret: null
      salesforce_password: null
      salesforce_username: null
      saveFormSessionLimit: 10
      saveFormTtl: 30
      scriptInsertLocation: footer
      scriptInsertType: pointers
      sessionContext: payload
      sessionContextCount: 100
      sessionContextSecret: ''
      sessionContextTimeToLiveMinutes: 180
      sessionEntryMaxCount: 50
      sessionEntryTTL: 10800
      showErrorsForBlockedEmails: false
      showErrorsForBlockedKeywords: false
      showTutorial: false
      spamFolderEnabled: true
      spamProtectionBehaviour: simulate_success
      submissionThrottlingCount: null
      submissionThrottlingTimeFrame: null
      successTemplateDirectory: null
      twigInHtml: true
      twigInHtmlIsolatedMode: true
      updateSearchIndexes: true
  sendgrid:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: Conversion-assesment
  schemaVersion: 3.7.33
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
